### PR TITLE
Setup podcodar linter

### PR DESCRIPTION
**Pull request by marco-souza**

### CODE REVIEW

**Review by vitorschelb — APPROVED** [review]
Great job! Thanks for the contributtion!

**Review by nicolasbrandao — APPROVED** [review]
Good job, well done!

**Review by nicolasbrandao — APPROVED** [review]
Good job, well done!

**Review by nicolasbrandao — APPROVED** [review]
Good job, well done!

**Review by nicolasbrandao — APPROVED** [review]
Good job, well done!

**Review by nicolasbrandao — APPROVED** [review]
Good job, well done!

**Comment by marco-souza** [comment]
Thanks guys! Merging it.

**Pull request merged**
